# Generated by Django 4.2.11 on 2024-05-04 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aniolectivo',
            fields=[
                ('Codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('Fecha_inicio', models.DateField()),
                ('Fecha_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('Id_categoria', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('Nombre_categoria', models.CharField(max_length=50)),
                ('Descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Colegio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo', models.CharField(max_length=10, unique=True)),
                ('Nombre', models.CharField(max_length=100)),
                ('Rector', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('Id_empleado', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('Apellido_paterno', models.CharField(max_length=35)),
                ('Apellido_materno', models.CharField(max_length=35)),
                ('Nombres', models.CharField(max_length=35)),
                ('Genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1)),
                ('Cargo', models.CharField(choices=[('E', 'Empleado'), ('A', 'Administrador')], max_length=15)),
                ('Telefono', models.CharField(max_length=15)),
                ('Correo_electronico', models.EmailField(max_length=50)),
                ('Direccion', models.CharField(max_length=50)),
                ('Activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('Id_estudiante', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('Apellido', models.CharField(max_length=35)),
                ('Nombres', models.CharField(max_length=35)),
                ('Genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1)),
                ('Telefono', models.CharField(max_length=15)),
                ('Correo_electronico', models.EmailField(max_length=50)),
                ('Direccion', models.CharField(max_length=50)),
                ('Activo', models.BooleanField(default=True)),
                ('Alergias', models.CharField(blank=True, max_length=255, null=True)),
                ('Colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Modulo_1.colegio')),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('Id_profesor', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('Apellido_paterno', models.CharField(max_length=35)),
                ('Apellido_materno', models.CharField(max_length=35)),
                ('Nombres', models.CharField(max_length=35)),
                ('Genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1)),
                ('Telefono', models.CharField(max_length=15)),
                ('Correo_electronico', models.EmailField(max_length=50)),
                ('Direccion', models.CharField(max_length=50)),
                ('Activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('Id_proveedor', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('Ciudad', models.CharField(max_length=35)),
                ('Direccion', models.CharField(max_length=50)),
                ('Telefono', models.CharField(max_length=15)),
                ('Correo_electronico', models.EmailField(max_length=50)),
                ('Contacto', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('Id_producto', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('Imagen_Producto', models.ImageField(default='no_disponible.jpg', upload_to='Productos/')),
                ('Nombre', models.CharField(max_length=50)),
                ('Stock', models.IntegerField()),
                ('Precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Descripcion', models.CharField(max_length=255)),
                ('Fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('Disponible', models.BooleanField(default=True)),
                ('Proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Modulo_1.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateTimeField(auto_now_add=True)),
                ('Estado_pedido', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('ENVIADO', 'Enviado'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=10)),
                ('Categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Modulo_1.categoria')),
                ('Empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Modulo_1.empleado')),
                ('Estudiante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Modulo_1.estudiante')),
                ('Profesor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Modulo_1.profesor')),
            ],
        ),
        migrations.CreateModel(
            name='Padre',
            fields=[
                ('Id_padre', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('Correo_electronico', models.EmailField(max_length=50)),
                ('Telefono', models.CharField(max_length=15)),
                ('Recomendaciones', models.CharField(max_length=255)),
                ('Estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Modulo_1.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialPedido',
            fields=[
                ('Id_historial_pedido', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('Fecha_entrega', models.DateField()),
                ('Estado_entrega', models.CharField(max_length=10)),
                ('Pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Modulo_1.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('Codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('Aniolectivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Modulo_1.aniolectivo', verbose_name='Año lectivo')),
            ],
        ),
        migrations.AddField(
            model_name='estudiante',
            name='Grado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Modulo_1.grado'),
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad', models.IntegerField()),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Modulo_1.pedido')),
                ('Producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Modulo_1.producto')),
            ],
        ),
        migrations.CreateModel(
            name='ComentarioProducto',
            fields=[
                ('Id_comentario', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('Comentario', models.CharField(max_length=255)),
                ('Fecha', models.DateTimeField(auto_now_add=True)),
                ('Estudiante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Modulo_1.estudiante')),
                ('Producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Modulo_1.producto')),
                ('Profesor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Modulo_1.profesor')),
            ],
        ),
        migrations.CreateModel(
            name='Almuerzo',
            fields=[
                ('Id_almuerzo', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('Fecha', models.DateField()),
                ('Detalle', models.CharField(max_length=255)),
                ('Precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Modulo_1.estudiante')),
            ],
        ),
    ]
