# Generated by Django 4.2.11 on 2024-05-07 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Modulo_1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='padre',
            name='cliente_id',
        ),
        migrations.RemoveField(
            model_name='padre',
            name='usuario',
        ),
        migrations.AddField(
            model_name='padre',
            name='cliente',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='Modulo_1.cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='padre',
            name='hijos',
            field=models.ManyToManyField(related_name='padres', to='Modulo_1.cliente'),
        ),
    ]
