# Generated by Django 4.2.11 on 2024-05-07 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modulo_1', '0002_remove_cliente_usuario_remove_padre_cliente_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
