# Generated by Django 4.2.11 on 2024-05-11 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modulo_1', '0002_venta_detalleventa'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='desglosar_iva',
            field=models.BooleanField(default=False),
        ),
    ]
